# Generated by Django 3.1.1 on 2020-10-20 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_order_code_refund'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='code_refund',
        ),
    ]
