# Generated by Django 3.1.1 on 2020-10-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_order_code_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code_refund',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
