# Generated by Django 3.1.1 on 2020-10-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_order_code_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code_refund',
            field=models.CharField(max_length=50),
        ),
    ]
