# Generated by Django 3.1.1 on 2020-10-20 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_auto_20201020_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='code',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='message',
        ),
        migrations.AddField(
            model_name='refund',
            name='messages',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
