# Generated by Django 3.0.10 on 2020-09-09 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.CharField(blank=True, choices=[('0', 'onl'), ('1', 'off')], max_length=1),
        ),
    ]
