# Generated by Django 3.0.10 on 2020-09-09 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_class',
            field=models.ManyToManyField(blank=True, to='student.course'),
        ),
    ]
